#!/usr/bin/env python3
"""Reconstruct a Claude Code session's verbatim conversation — plus any ancestor
sessions it resumes from — into one clean transcript, oldest-first.

Why this exists: the `recap` skill needs the *dialogue* of a past session back in
context so the user can continue it. The raw JSONL on disk is mostly tool I/O
(file dumps, command output, thinking) — bloat that drowns the actual turns. This
script parses the JSONL, walks the resume-chain backward, strips the noise, and
writes only the verbatim user/assistant dialogue to a temp file. The skill reads
that file. Nothing is regenerated by a model, so it is fast and exact.

Usage:  recap.py <session-uuid (or any text containing one)>
Writes the transcript to /tmp/recap-<newest-uuid>.txt and prints a short summary
(the session chain, the output path, its size) to stdout.
"""
import glob
import json
import os
import re
import sys

PROJECTS = os.path.expanduser("~/.claude/projects")

UUID_RE = re.compile(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b")
TRIGGER_RE = re.compile(r"(이어서|context|불러와|다시\s*읽|전부\s*읽|다\s*읽|resume|recap)", re.IGNORECASE)
SR_RE = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)
STDOUT_RE = re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.DOTALL)
CMD_RE = re.compile(r"<command-name>\s*(.*?)\s*</command-name>", re.DOTALL)
ARGS_RE = re.compile(r"<command-args>\s*(.*?)\s*</command-args>", re.DOTALL)


def locate(uuid):
    hits = glob.glob(os.path.join(PROJECTS, "*", uuid + ".jsonl"))
    return hits[0] if hits else None


def load(path):
    """Conversation rows only: real user/assistant turns, no subagent sidechains."""
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            try:
                o = json.loads(line)
            except json.JSONDecodeError:
                continue
            if o.get("type") in ("user", "assistant") and not o.get("isSidechain"):
                rows.append(o)
    return rows


def is_noise(o):
    # injected meta turns and API-error turns ("Prompt is too long") aren't dialogue
    return o.get("isMeta") or o.get("isApiErrorMessage")


def msg_text(o):
    content = (o.get("message") or {}).get("content")
    if isinstance(content, str):
        return content
    return "".join(
        b.get("text", "") for b in content
        if isinstance(b, dict) and b.get("type") == "text"
    )


def superseded(rows):
    """uuids of abandoned edit/resend branches.

    Editing a prompt appends a second user message under the *same* parentUuid;
    the later sibling is the one the user kept. Mark earlier same-parent user
    siblings — and everything descending from them — as abandoned, so the
    line-order pass drops the dead branch without losing the live conversation.

    Line-order (not a root-to-leaf tree walk) is deliberate: real sessions
    fragment into many roots at context-compaction and error boundaries, so a
    single tree path would silently drop most of the dialogue. We keep every
    line and only prune the branches we can prove were superseded.
    """
    children = {}
    for o in rows:
        children.setdefault(o.get("parentUuid"), []).append(o)

    dead = set()
    for kids in children.values():
        users = [k for k in kids if (k.get("message") or {}).get("role") == "user"]
        for k in users[:-1]:
            dead.add(k.get("uuid"))

    changed = True
    while changed:
        changed = False
        for o in rows:
            u = o.get("uuid")
            if u not in dead and o.get("parentUuid") in dead:
                dead.add(u)
                changed = True
    return dead


def find_parent(rows, self_id):
    """A session resumes another when one of its opening user prompts pastes a
    UUID alongside resume language. Strip echoed command output first — a recall/
    recap result quoted back into the next turn is a frequent false positive."""
    seen = 0
    for o in rows:
        if is_noise(o) or (o.get("message") or {}).get("role") != "user":
            continue
        seen += 1
        if seen > 8:
            break
        probe = STDOUT_RE.sub("", SR_RE.sub("", msg_text(o)))
        m = UUID_RE.search(probe)
        if m and m.group(0) != self_id and TRIGGER_RE.search(probe):
            return m.group(0)
    return None


def build_chain(start):
    chain, cur, seen = [], start, set()
    while cur and cur not in seen and len(chain) < 10:
        seen.add(cur)
        path = locate(cur)
        if not path:
            break
        rows = load(path)
        chain.append((cur, path, rows))
        cur = find_parent(rows, cur)
    chain.reverse()
    return chain


def cwd_of(rows):
    for o in rows:
        if o.get("cwd"):
            return o["cwd"]
    return "?"


def render(rows):
    dead = superseded(rows)
    turns = []
    for o in rows:
        if is_noise(o) or o.get("uuid") in dead:
            continue
        role = (o.get("message") or {}).get("role")
        content = (o.get("message") or {}).get("content")
        blocks = [{"type": "text", "text": content}] if isinstance(content, str) else content
        for b in blocks:
            if not isinstance(b, dict):
                continue
            kind = b.get("type")
            if kind == "text":
                text = b.get("text", "")
                cmd = CMD_RE.search(text)
                if cmd:
                    args = ARGS_RE.search(text)
                    turns.append(("cmd", ("· " + cmd.group(1) + ((" " + args.group(1)) if args else "")).strip()))
                    continue
                text = STDOUT_RE.sub("", SR_RE.sub("", text)).strip()
                if text:
                    turns.append(("User" if role == "user" else "Assistant", text))
            elif kind == "tool_use":
                hint = json.dumps(b.get("input", {}), ensure_ascii=False)[:80].replace("\n", " ")
                turns.append(("tool", "· %s %s" % (b.get("name"), hint)))
            # thinking / tool_result: dropped — this is the noise we strip
    return turns


def build_transcript(chain):
    out = ["세션 %d개 체인. 오래된 것부터 원문 그대로. tool 노이즈는 뺐어.", ""]
    for i, (sid, _path, rows) in enumerate(chain, 1):
        out.append("═══ 세션 %d/%d — %s · cwd: %s ═══" % (i, len(chain), sid, cwd_of(rows)))
        for role, text in render(rows):
            out.append(text if role in ("tool", "cmd") else "\n[%s]\n%s" % (role, text))
        out.append("")
    out.append("어디서 이어갈까?")
    return "\n".join(out)


def main():
    if len(sys.argv) < 2:
        print("usage: recap.py <session-uuid>", file=sys.stderr)
        return 2

    m = UUID_RE.search(sys.argv[1].lower())
    if not m:
        print("인자에서 세션 UUID를 못 찾았어: %r" % sys.argv[1], file=sys.stderr)
        return 2
    start = m.group(0)

    chain = build_chain(start)
    if not chain:
        print("이 ID는 디스크에 없어: %s" % start, file=sys.stderr)
        return 1

    body = build_transcript(chain)
    out_path = "/tmp/recap-%s.txt" % chain[-1][0]
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(body)

    print("OK — 세션 %d개 체인 복원" % len(chain))
    for i, (sid, _path, rows) in enumerate(chain, 1):
        print("  %d/%d  %s  · %s" % (i, len(chain), sid, cwd_of(rows)))
    print("transcript: %s" % out_path)
    print("size: %d chars, %d lines" % (len(body), body.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
