#!/usr/bin/env bash
# PreToolUse hook: block direct edits to npm/pnpm/yarn/bun lockfiles.
# Lockfiles must be regenerated by the package manager (npm/pnpm/yarn/bun add)
# so the manifest, version range, and lockfile stay in sync.

set -euo pipefail

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name')

LOCKFILE_BASES_RE='^(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb|bun\.lock)$'
LOCKFILES_RE='package-lock\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb|bun\.lock'

deny() {
  jq -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

case "$TOOL" in
  Write|Edit)
    PATH_TO_CHECK=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')
    BASE=$(basename "$PATH_TO_CHECK")
    if [[ "$BASE" =~ $LOCKFILE_BASES_RE ]]; then
      deny "Direct edit of lockfile $PATH_TO_CHECK is blocked. Use the package manager (npm/pnpm/yarn/bun add) so the lockfile is regenerated atomically. See @instructions/package-json-dependencies.md."
    fi
    ;;
  Bash)
    CMD=$(echo "$INPUT" | jq -r '.tool_input.command')
    # Match write indicators (redirect / in-place edit / overwrite) followed
    # by a lockfile name in the same shell statement (no ; | & in between).
    if echo "$CMD" | grep -qE "(>|>>|\btee\b|sed[[:space:]]+-i|awk[[:space:]]+-i|perl[[:space:]]+-i|cp[[:space:]]|mv[[:space:]])[^;|&]*($LOCKFILES_RE)"; then
      deny "This Bash command appears to modify a lockfile directly. Use the package manager (npm/pnpm/yarn/bun add) instead so the lockfile is regenerated atomically. See @instructions/package-json-dependencies.md."
    fi
    ;;
esac

exit 0
