import argparse
import json
from pathlib import Path
import re


def section(path, source):
    body = path.read_text()
    paths = []
    if body.startswith("---\n"):
        _, metadata, body = body.split("---", 2)
        for line in metadata.splitlines():
            if line.startswith("paths:"):
                paths = json.loads(line.removeprefix("paths:").strip())
                if not isinstance(paths, list) or not all(isinstance(p, str) for p in paths):
                    raise ValueError(f"{path}: paths must be an inline JSON string array")

    lines = []
    fence = None
    for line in body.strip().splitlines():
        marker = re.match(r"^\s*(`{3,}|~{3,})", line)
        if marker:
            token = marker.group(1)
            if fence is None:
                fence = token
            elif token[0] == fence[0] and len(token) >= len(fence):
                fence = None
        if fence is None and re.match(r"^#{1,5} ", line):
            line = "#" + line
        lines.append(line)

    if paths:
        scope = ", ".join(f"`{path}`" for path in paths)
        lines[1:1] = ["", f"Applies when working with files matching: {scope}."]

    return f"<!-- Source: {source} -->\n\n" + "\n".join(lines)


def render(repo):
    header = (
        "# Codex global instructions\n\n"
        "The shared rules and Codex-specific instructions below are included in full. "
        "Apply each rule within the situation and subject it governs. File scopes describe "
        "applicability; all instruction text is already present in this file.\n\n"
        "<!-- Generated by scripts/sync-codex-instructions.py. Edit the source files, then regenerate. -->"
    )
    roots = (
        (repo / "packages/agents/.agents/rules", "~/.agents/rules"),
        (repo / "packages/codex/.codex/instructions", "~/.codex/instructions"),
    )
    sections = [section(path, f"{source}/{path.name}")
                for root, source in roots for path in sorted(root.glob("*.md"))]
    return "\n\n".join([header, *sections]) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    target = repo / "packages/codex/.codex/AGENTS.md"
    expected = render(repo)
    if options.check:
        if target.read_text() != expected:
            raise SystemExit("Codex AGENTS.md is stale; run scripts/sync-codex-instructions.py")
        print("Codex AGENTS.md matches all instruction sources")
        return

    target.write_text(expected)
    print(f"Generated {target} ({len(expected.encode())} bytes)")


if __name__ == "__main__":
    main()
